### ISSUE TITLE
the speed of the Video Harmonization

### ISSUE THREAD

**Issue by AmberCheng** [ZHKKKe/Harmonizer#4]
Hi,
 Thanks for your wonderful work. 
I have tried the Video Harmonization demo on GPU recently, and I found the speed is about 150ms/bs=1(1920x1080).  But I remember this model can reach real-time performance at Full HD resolution. Are there any points I missed?

**Comment by ZHKKKe** [comment]
Hi, Thanks for your attention.
We follow the most works to measure only model inference time. In the demo, the data loader also takes time to load the video frames, which is usually slow. You need to implement a parallel data loader to hide this kind of time consuming.

**Comment by AmberCheng** [comment]
> Hi, Thanks for your attention. We follow the most works to measure only model inference time. In the demo, the data loader also takes time to load the video frames, which is usually slow. You need to implement a parallel data loader to hide this kind of time consuming.

Thanks for your kindly reply. I have measure only model inference time and it is about 65fps.  I will try to accelerate other parts.
